In [1]:
arr=[1,2,3,4]
arr

[1, 2, 3, 4]

In [2]:
arr.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [3]:
arrs=np.array(arr)

NameError: name 'np' is not defined

In [4]:
pip install numpy

     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.2 kB 178.6 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 251.1 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 1.1 MB/s eta 0:00:15
   ---------------------------------------- 0.1/15.8 MB 871.5 kB/s eta 0:00:19
   ---------------------------------------- 0.2/15.8 MB 1.3 MB/s eta 0:00:12
    --------------------------------------- 0.3/15.8 MB 1.4 MB/s eta 0:00:11
    --------------------------------------- 0.3/15.8 MB 1.4 MB/s eta 0:00:12
   - -------------------------------------- 0.4/15.8 MB 1.6 MB/s eta 0:00:10
   - ----------

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'



In [5]:
import numpy as np

In [6]:
arrs=np.array(arr)

In [7]:
arrs.dtype

dtype('int32')

In [8]:
random_int_array = np.random.randint(1, 50, size=3)

In [9]:
random_int_array

array([30, 29, 15])

In [10]:
random_int_array = np.random.randint(1, 50, size=10)
random_int_array

array([49, 23, 29, 11, 13, 16, 44, 29,  5,  8])

In [11]:
random_int_array.size

10

In [12]:
random_int_array.np.ndim

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [13]:
np.ndim(random_int_array)

1

In [14]:
two_dim = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])

In [15]:
tow_dim

NameError: name 'tow_dim' is not defined

In [16]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])