In [1]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.0 kB 660.6 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 540.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 1.3 MB/s eta 0:00:13
   ---------------------------------------- 0.1/15.8 MB 787.7 kB/s eta 0:00:20
   ---------------------------------------- 0.1/15.8 MB 819.2 kB/s eta 0:00:20
   ---------------------------------------- 0.2/15.8 MB 913.1 kB/s eta 0:00:18
    --------------------------------------- 0.2/15.8 MB 1.1 MB/s eta 0:00:15
    --------------------------------------- 0.3/15.8 MB 1.1 MB/s eta 0:00:15
    --------------------------------------- 0.4/15.8 MB 1.2 MB/s eta 0:00:14
   - -------------------------------------- 0.4/15.8 MB 1.1 MB/s eta 0:00

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
random_int_array = np.random.randint(1, 50, size=10)
random_int_array

array([47, 33, 40, 46, 22, 26, 20, 45, 13, 40])

In [5]:
m=np.mean(random_int_array)
m

33.2

In [8]:
arr1=[[1,2,3],
      [4,5,6],
      [7,8,9]]
arr2=[[1,2,3],
      [4,5,6],
      [7,8,9]]
_12=np.add(arr1,arr2)
_12

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [10]:
m=np.mean(_12)
m

10.0

In [21]:
arr3=np.random.randint(1,100, size=20)
arr3
cond= arr3>50
filtered_arr=arr3[cond]
filtered_arr

array([90, 63, 75, 62, 68, 68, 98, 86, 84])

In [37]:
arr4=[1,2,3,4,5,6,7,8,9]
np.random.shuffle(arr4)
arr4
num = np.random.randint(0,9)
num
arr4[num]

3